version: '3'
services:
  cff-dependency-dashboard:
    build:
      context: .
      target: development
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
